# Generated by Django 4.0.4 on 2022-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mobilephone', models.CharField(max_length=128)),
                ('other_contact', models.CharField(max_length=128)),
                ('other_contact2', models.CharField(max_length=128)),
                ('memo', models.CharField(max_length=256)),
            ],
        ),
    ]
